version: '3'

services:
  mariadb:
      image: mariadb
      volumes:
        - ./db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: qwer1234
        MYSQL_DATABASE: keycloak
        MYSQL_USER: kcuser
        MYSQL_PASSWORD: qwer1234
      # Copy-pasted from https://github.com/docker-library/mariadb/issues/94
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent"]
      ports:
        - "13306:3306"
  keycloak:
      image: jboss/keycloak
      ports:
        #- "18080:8080"
        - "8543:8443"
      environment:
        DB_VENDOR: mariadb
        DB_ADDR: mariadb
        DB_DATABASE: keycloak
        DB_USER: kcuser
        DB_PASSWORD: qwer1234
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: qwer1234
        #JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
        #JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500
        KEYCLOAK_IMPORT: /tmp/realm_export/bicman-hospital.json
      volumes:
        - "./cert/:/etc/x509/https/"
        - "./keycloak_volume:/tmp"
        - "./realm_export:/tmp/realm_export"
      depends_on:
        - mariadb
